# Temel Java imajı
FROM openjdk:21-jdk-slim

# Kaynak kodu ve pom.xml'i kopyala
COPY . .

# Maven ile projeyi derle
RUN ./mvnw clean package -DskipTests

# JAR dosyasını çalışma dizinine kopyala
COPY target/webbackend-0.0.1-SNAPSHOT.jar app.jar

# Uygulamayı çalıştır
ENTRYPOINT ["java", "-jar", "/app.jar"]
